'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');
const c=require('../app/lib/core.cjs');const t=require('../app/lib/tools.cjs');
const id='AbCdEf_12-3',canonical=`https://www.youtube.com/watch?v=${id}`;
for(const input of [`https://youtu.be/${id}?si=tracking`,`youtube.com/watch?v=${id}&list=PLx`,`https://www.youtube.com/shorts/${id}`,`https://m.youtube.com/live/${id}`,`http://youtube.com/embed/${id}`])test('canonicalizes '+input,()=>assert.equal(c.normalizeUrl(input),canonical));
for(const input of ['https://youtube.com.evil.org/watch?v='+id,'file:///etc/passwd','https://example.com','https://user:pass@youtube.com/watch?v='+id,'https://youtube.com:8080/watch?v='+id,'https://youtube.com/playlist?list=x','--exec=evil','https://youtu.be/short','https://youtube.com/watch?v=x\n--exec x'])test('rejects unsafe or non-video input '+input,()=>assert.throws(()=>c.normalizeUrl(input)));
test('deduplicates links',()=>assert.deepEqual(c.normalizeUrls(canonical+'\nhttps://youtu.be/'+id),[canonical]));
test('blank links rejected',()=>assert.throws(()=>c.normalizeUrls('\n')));
test('21 links rejected',()=>assert.throws(()=>c.normalizeUrls(Array(21).fill(canonical))));
test('nontext links rejected',()=>assert.throws(()=>c.normalizeUrls([{}])));
for(const mode of ['mp4','mkv'])test(mode+' honors 1080 cap',()=>{const s=c.formatSelector(mode,'1080');assert(s.includes('height<=1080'));assert(!s.includes('height<=2160'));});
test('best quality uncapped',()=>assert(!c.formatSelector('mp4','best').includes('height')));
test('MP3 uses audio stream',()=>assert.equal(c.formatSelector('mp3','1080'),'ba/b'));
test('invalid mode rejected',()=>assert.throws(()=>c.formatSelector('exe','1080')));
test('invalid height rejected',()=>assert.throws(()=>c.formatSelector('mp4','1080;evil')));
test('auth defaults none',()=>assert.deepEqual(c.validateAuth(),{mode:'none'}));
test('auth requires consent',()=>assert.throws(()=>c.validateAuth({mode:'browser',browser:'chrome'})));
test('auth strips unrecognized keys',()=>{const a=c.validateAuth({mode:'browser',consent:true,browser:'chrome',password:'do-not-keep',args:['--exec','bad']});assert(!a.password&&!a.args);});
test('browser profile with spaces safe in one argument',()=>{const a=c.validateAuth({mode:'browser',consent:true,browser:'chrome',profile:'Profile 1'});assert.equal(c.browserSpec(a),'chrome:Profile 1');});
test('profile container injection rejected',()=>assert.throws(()=>c.validateAuth({mode:'browser',consent:true,browser:'chrome',profile:'Default::other'})));
test('Firefox container separated',()=>{const a=c.validateAuth({mode:'browser',consent:true,browser:'firefox',profile:'default',container:'Work'});assert.equal(c.browserSpec(a),'firefox:default::Work');});
test('Safari rejected on Windows',()=>assert.throws(()=>c.validateAuth({mode:'browser',consent:true,browser:'safari'},'win32')));
test('relative cookie file rejected',()=>assert.throws(()=>c.validateAuth({mode:'file',consent:true,file:'cookies.txt'})));
const cookie='# Netscape HTTP Cookie File\n.youtube.com\tTRUE\t/\tTRUE\t2147483647\tSID\tsecret_session_123\n.evil.org\tTRUE\t/\tTRUE\t2147483647\tSESSION\texclude-this\n#HttpOnly_.google.com\tTRUE\t/\tTRUE\t0\tHSID\tkeep-google\n';
test('cookie whitelist excludes unrelated sites',()=>{const s=c.cookieSubset(cookie);assert(s.text.includes('.youtube.com'));assert(s.text.includes('#HttpOnly_.google.com'));assert(!s.text.includes('evil.org'));});
test('cookie domain suffix spoof rejected',()=>assert.throws(()=>c.cookieSubset('# Netscape HTTP Cookie File\nyoutube.com.evil.org\tTRUE\t/\tTRUE\t0\tX\tx\n')));
test('non Netscape file rejected',()=>assert.throws(()=>c.cookieSubset('{"token":"x"}')));
test('malformed cookie row rejected',()=>assert.throws(()=>c.cookieSubset('# Netscape HTTP Cookie File\ninvalid\n')));
test('cookie header redaction',()=>assert(!c.redact('Cookie: SID=secret-value').includes('secret-value')));
test('bearer redaction',()=>assert(!c.redact('Authorization: Bearer secret').includes('secret')));
test('explicit secrets redacted',()=>assert.equal(c.redact('path /my/private/cookie.txt',['/my/private/cookie.txt']),'path [비공개]'));
test('signed URL params not in log',()=>assert(!c.redact('https://rr.googlevideo.com/videoplayback?signature=secret').includes('secret')));
test('auth file context copies only allowed domains then cleans',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'ts-test-'));try{const source=path.join(root,'original.txt');await fs.writeFile(source,cookie);const ctx=await c.authContext({mode:'file',consent:true,file:source},path.join(root,'private'));const temporary=ctx.args[1];assert.notEqual(temporary,source);assert(!(await fs.readFile(temporary,'utf8')).includes('evil.org'));await ctx.cleanup();await assert.rejects(fs.stat(temporary));assert.equal(await fs.readFile(source,'utf8'),cookie);}finally{await fs.rm(root,{recursive:true,force:true});}});
test('progress payload parsed',()=>assert.deepEqual(c.parseEvent('__TS_PROGRESS__{"downloaded":1}'),{kind:'progress',data:{downloaded:1}}));
test('invalid progress type ignored',()=>assert.equal(c.parseEvent('__TS_PROGRESS__[]'),null));
test('invalid file payload ignored',()=>assert.equal(c.parseEvent('__TS_FILE__{}'),null));
test('malformed JSON ignored',()=>assert.equal(c.parseEvent('__TS_META__{'),null));
test('relative path escape prevented',()=>assert(!c.inside('/tmp/work','/tmp/work-sibling/file')));
test('valid child path accepted',()=>assert(c.inside('/tmp/work','/tmp/work/file')));
test('unknown totals remain indeterminate',()=>{assert.equal(c.number(null),null);assert.equal(c.number('NA'),null);assert.equal(c.number(-1),null);assert.equal(c.number(0),0);});
test('existing files never overwritten',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'ts-publish-'));try{const work=path.join(root,'work');await fs.mkdir(work);await fs.writeFile(path.join(root,'video.mp4'),'old');await fs.writeFile(path.join(work,'video.mp4'),'new');const p=await c.publishFile(path.join(work,'video.mp4'),root);assert.equal(path.basename(p),'video (1).mp4');assert.equal(await fs.readFile(path.join(root,'video.mp4'),'utf8'),'old');assert.equal(await fs.readFile(p,'utf8'),'new');}finally{await fs.rm(root,{recursive:true,force:true});}});
test('download allowlist blocks malicious domains',()=>{for(const u of ['http://github.com/test','https://github.com.attacker.test/a','https://user:pass@github.com/a','https://example.org/x'])assert.throws(()=>t.validDownloadUrl(u));});
test('download allowlist accepts GitHub and PyPI CDN',()=>{assert(t.validDownloadUrl('https://release-assets.githubusercontent.com/test'));assert(t.validDownloadUrl('https://files.pythonhosted.org/file'));});
test('checksums use exact filename match',()=>{const sum='a'.repeat(64);assert.equal(t.sumFor(sum+'  file.exe\n','file.exe'),sum);assert.throws(()=>t.sumFor(sum+'  other.exe','file.exe'));});
test('selects native Apple Silicon FFmpeg',()=>{const f='imageio_ffmpeg-1.0-py3-none-macosx_11_0_arm64.whl';assert.equal(t.pickWheel({urls:[{filename:f,packagetype:'bdist_wheel'}]},'darwin','arm64').filename,f);});
test('selects Windows x64 wheel',()=>{const f='imageio_ffmpeg-1.0-py3-none-win_amd64.whl';assert.equal(t.pickWheel({urls:[{filename:f,packagetype:'bdist_wheel'}]},'win32','x64').filename,f);});
test('missing wheel explicitly fails',()=>assert.throws(()=>t.pickWheel({urls:[]},'darwin','arm64')));
test('unsupported Windows ARM rejected',()=>assert.throws(()=>t.pickWheel({urls:[]},'win32','arm64')));
test('corrupt zip rejected',()=>assert.throws(()=>t.zipEntries(Buffer.from('invalid'))));
test('Windows cookie crypto errors have actionable explanation',()=>assert(c.friendlyError('failed to decrypt with DPAPI').includes('Firefox')));
