'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');
const {Engine,Service}=require('../app/lib/service.cjs');const {Cancelled}=require('../app/lib/core.cjs');
const {runProcess}=require('../app/lib/process.cjs');
const url='https://www.youtube.com/watch?v=AbCdEf_12-3';
const tools={health:{ready:true,yt_dlp:'test'},busy:false,ytdlp:'fixture-downloader',ffmpeg:process.env.TS_TEST_FFMPEG||'/usr/bin/ffmpeg',async init(){}};
const wait=async(f)=>{const start=Date.now();while(!f()){if(Date.now()-start>5000)throw Error('condition timeout');await new Promise(r=>setTimeout(r,10));}};
async function setup(engine){const root=await fs.mkdtemp(path.join(os.tmpdir(),'ts-service-'));const service=new Service(engine,tools,path.join(root,'data'),root);await service.init();return {root,service,cleanup:async()=>{await service.close();await fs.rm(root,{recursive:true,force:true});}};}
test('engine command preserves 4K cap and isolates output',()=>{const e=new Engine(tools,'/tmp/auth');const a=e.command({mode:'mp4',quality:'2160'},'/tmp/work path');assert(a.includes('node:'+process.execPath));assert(a.includes('--no-plugin-dirs'));assert(a[a.indexOf('--format')+1].includes('height<=2160'));assert(a[a.indexOf('--output')+1].startsWith('/tmp/work path/'));});
test('engine metadata sanitizes output and skips DRM heights',async()=>{const runner=async(exe,args,o)=>{o.onLine(JSON.stringify({title:'테스트 영상',formats:[{height:1080},{height:2160,has_drm:true}]}));return 0;};const e=new Engine(tools,'/tmp/auth',{runner});const data=await e.inspect(url,{mode:'none'},new AbortController().signal);assert.deepEqual(data.heights,[1080]);assert.equal(data.title,'테스트 영상');assert(data.access_note.includes('보장'));});
test('engine refuses live metadata',async()=>{const e=new Engine(tools,'/tmp/auth',{runner:async(_e,_a,o)=>{o.onLine('{"is_live":true}');return 0;}});await assert.rejects(e.inspect(url,{mode:'none'},new AbortController().signal),/라이브/);});
test('download uses unique staging and publishes a real file',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'ts-engine-'));let args;try{const e=new Engine(tools,path.join(root,'auth'),{runner:async(_e,a,o)=>{args=a;const work=path.dirname(a[a.indexOf('--output')+1]);const file=path.join(work,'영상.mp4');await fs.writeFile(file,'video fixture');o.onLine('__TS_META__{"title":"영상"}');o.onLine('__TS_FILE__'+JSON.stringify(file));return 0;}});const result=await e.download({id:'1',url,mode:'mp4',quality:'1080',folder:root},{mode:'none'},new AbortController().signal,()=>{},()=>{});assert.equal(await fs.readFile(result.file,'utf8'),'video fixture');assert.equal(args.at(-2),'--');assert.equal(args.at(-1),url);assert(!(await fs.readdir(root)).some(n=>n.startsWith('.tubesave-partial-')));}finally{await fs.rm(root,{recursive:true,force:true});}});
test('download rejects an engine path escape',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'ts-escape-'));try{const e=new Engine(tools,path.join(root,'auth'),{runner:async(_e,_a,o)=>{o.onLine('__TS_FILE__"/etc/passwd"');return 0;}});await assert.rejects(e.download({url,mode:'mp4',quality:'1080',folder:root},{mode:'none'},new AbortController().signal,()=>{},()=>{}),/경로/);}finally{await fs.rm(root,{recursive:true,force:true});}});
test('real FFmpeg MP3 conversion through engine',async(t)=>{try{await fs.access(tools.ffmpeg);}catch{t.skip('FFmpeg unavailable');return;}const root=await fs.mkdtemp(path.join(os.tmpdir(),'ts-mp3-'));try{const e=new Engine(tools,path.join(root,'auth'),{runner:async(exe,args,o)=>{if(exe!==tools.ytdlp)return runProcess(exe,args,o);const work=path.dirname(args[args.indexOf('--output')+1]),file=path.join(work,'tone.wav');await runProcess(tools.ffmpeg,['-hide_banner','-nostdin','-f','lavfi','-i','sine=frequency=440:duration=0.15','-y',file]);o.onLine('__TS_META__{"title":"테스트 오디오","duration":0.15}');o.onLine('__TS_FILE__'+JSON.stringify(file));return 0;}});const result=await e.download({url,mode:'mp3',quality:'1080',folder:root},{mode:'none'},new AbortController().signal,()=>{},()=>{});assert(result.file.endsWith('.mp3'));assert(result.size>500);}finally{await fs.rm(root,{recursive:true,force:true});}});
test('queue is serial and history omits secrets and logs',async()=>{let active=0,max=0;const engine={ready(){},async download(j,a,s,u,l){max=Math.max(max,++active);assert.equal(a.browser,'chrome');l('transient log');await new Promise(r=>setTimeout(r,20));active--;return {file:path.join(j.folder,j.id+'.mp4'),size:5};}};const f=await setup(engine);try{await f.service.enqueue({urls:url+'\nhttps://youtu.be/ZyXwVu_98-7',folder:f.root,mode:'mp4',quality:'1080',auth:{mode:'browser',browser:'chrome',profile:'Private Profile',consent:true}});await wait(()=>!f.service.working);assert.equal(max,1);assert.equal(f.service.jobs.length,2);const h=await fs.readFile(path.join(f.root,'data','history.json'),'utf8');assert(!h.includes('Private Profile'));assert(!h.includes('transient log'));assert(!h.includes('auth'));assert.equal(f.service.secrets.size,0);}finally{await f.cleanup();}});
test('duplicates of active downloads excluded',async()=>{let release;const engine={ready(){},async download(){await new Promise(r=>release=r);return {file:'x',size:1};}};const f=await setup(engine);try{await f.service.enqueue({urls:url,folder:f.root});const out=await f.service.enqueue({urls:url,folder:f.root});assert.equal(out.skipped,1);assert.equal(out.added.length,0);release();await wait(()=>!f.service.working);}finally{await f.cleanup();}});
test('disconnect aborts authenticated active and queued jobs',async()=>{const engine={ready(){},download(j,a,signal){return new Promise((res,rej)=>{if(signal.aborted)return rej(new Cancelled());signal.addEventListener('abort',()=>rej(new Cancelled()),{once:true});});}};const f=await setup(engine);try{await f.service.enqueue({urls:url+'\nhttps://youtu.be/ZyXwVu_98-7',folder:f.root,auth:{mode:'browser',browser:'chrome',consent:true}});await f.service.resetAuth();await wait(()=>!f.service.working);assert(f.service.jobs.every(j=>j.status==='cancelled'));assert.equal(f.service.auth.mode,'none');assert.equal(f.service.secrets.size,0);}finally{await f.cleanup();}});
test('history clear does not delete videos',async()=>{const f=await setup({ready(){}});try{const file=path.join(f.root,'existing.mp4');await fs.writeFile(file,'preserve');f.service.jobs.push({id:'1',status:'done',file});await f.service.clearHistory();assert.equal(await fs.readFile(file,'utf8'),'preserve');}finally{await f.cleanup();}});
test('retry uses current auth not history credentials',async()=>{let seen;const engine={ready(){},async download(j,a){seen=a;return{file:'x',size:1};}};const f=await setup(engine);try{f.service.jobs.push({id:'retry-id',status:'failed',url,folder:f.root,mode:'mp4',quality:'1080',auth_label:'old session'});await f.service.retry({id:'retry-id',auth:{mode:'none'}});await wait(()=>!f.service.working);assert.deepEqual(seen,{mode:'none'});}finally{await f.cleanup();}});
test('disconnect wins a race while authenticated enqueue saves options',async()=>{let ran=false,release;const f=await setup({ready(){},async download(){ran=true;return{file:'x',size:1};}});try{f.service.saveSettings=()=>new Promise(r=>release=r);const pending=f.service.enqueue({urls:url,folder:f.root,auth:{mode:'browser',browser:'chrome',consent:true}});await f.service.resetAuth();release();await assert.rejects(pending,Cancelled);assert.equal(ran,false);assert.equal(f.service.jobs.length,0);}finally{await f.cleanup();}});
test('failed OS notification preserves a completed job',async()=>{const f=await setup({ready(){},async download(){return{file:'saved',size:1};}});try{f.service.onDone=()=>{throw Error('notification unavailable');};await f.service.enqueue({urls:url,folder:f.root});await wait(()=>!f.service.working);assert.equal(f.service.jobs[0].status,'done');}finally{await f.cleanup();}});

test('concurrent setting saves return their own immutable option snapshots',async()=>{const f=await setup({ready(){}});try{const [a,b]=await Promise.all([f.service.saveSettings({folder:f.root,mode:'mp4',quality:'720'}),f.service.saveSettings({folder:f.root,mode:'mp3',quality:'1080'})]);assert.equal(a.mode,'mp4');assert.equal(a.quality,'720');assert.equal(b.mode,'mp3');assert.equal(b.quality,'1080');}finally{await f.cleanup();}});
test('update maintenance blocks new video and inspect tasks',async()=>{const f=await setup({ready(){}});try{f.service.maintenance=true;await assert.rejects(f.service.enqueue({urls:url,folder:f.root}),/업데이트/);await assert.rejects(f.service.inspect({url}),/업데이트/);}finally{await f.cleanup();}});
test('update maintenance wins an enqueue settings race',async()=>{let release,ran=false;const f=await setup({ready(){},async download(){ran=true;return{file:'x',size:1};}});try{f.service.saveSettings=()=>new Promise(r=>release=r);const pending=f.service.enqueue({urls:url,folder:f.root});f.service.maintenance=true;release({folder:f.root});await assert.rejects(pending,Cancelled);assert.equal(ran,false);assert.equal(f.service.jobs.length,0);}finally{await f.cleanup();}});
